package Interfas;

import Base_De_Datos.DaoRegistro;
import clases.Descuento;
import clases.Tarifario;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AdministrarDescuentos extends javax.swing.JFrame {

    DaoRegistro daoRegistro = new DaoRegistro();

    public AdministrarDescuentos() {
        initComponents();
        jtbTarifario.setModel(imprimirDatos());
        jtfIDDescuento.setEditable(false);
        jtbTarifario.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent event) {
                JTable table = (JTable) event.getSource();
                Point point = event.getPoint();
                int row = table.rowAtPoint(point);
                if(event.getClickCount()==1){
                    jtfIDDescuento.setText(jtbTarifario.getValueAt(jtbTarifario.getSelectedRow(), 0).toString());
                    jtfTiempo.setText(jtbTarifario.getValueAt(jtbTarifario.getSelectedRow(), 1).toString());
                    jtfDescuento.setText(jtbTarifario.getValueAt(jtbTarifario.getSelectedRow(), 2).toString());
                }
            }
        });
    }

    private DefaultTableModel imprimirDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Descuento");
        modelo.addColumn("Tiempo (horas)");
        modelo.addColumn("Descuento (%)");
        List<Descuento> desc = daoRegistro.descSel();
        for (Descuento d : desc) {
            String id = String.valueOf(d.getId_descuento());
            String descu = String.format("%.2f", d.getDescuento());
            String tiempo = String.format("%.2f", d.getTiempo());
            modelo.addRow(new Object[]{id, descu, tiempo});
        }
        return modelo;
    }
    
    private void vaciar() {
        jtfDescuento.setText("");
        jtfIDDescuento.setText("");
        jtfTiempo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtRetroceder = new javax.swing.JButton();
        jbtActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTarifario = new javax.swing.JTable();
        jtfIDDescuento = new javax.swing.JTextField();
        jtfDescuento = new javax.swing.JTextField();
        jtfTiempo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtInsertar = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 35, 35));

        jbtRetroceder.setBackground(new java.awt.Color(36, 35, 35));
        jbtRetroceder.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.jpeg"))); // NOI18N
        jbtRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRetrocederActionPerformed(evt);
            }
        });

        jbtActualizar.setBackground(new java.awt.Color(249, 127, 6));
        jbtActualizar.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtActualizar.setText("Actualizar");
        jbtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActualizarActionPerformed(evt);
            }
        });

        jtbTarifario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTarifario);

        jtfIDDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfIDDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIDDescuentoKeyTyped(evt);
            }
        });

        jtfDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jtfTiempo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Descuento");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descuento:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tiempo");

        jbtInsertar.setBackground(new java.awt.Color(249, 127, 6));
        jbtInsertar.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtInsertar.setText("Agregar");
        jbtInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInsertarActionPerformed(evt);
            }
        });

        jbtEliminar.setBackground(new java.awt.Color(249, 127, 6));
        jbtEliminar.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtRetroceder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jtfIDDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jtfTiempo)
                            .addComponent(jtfDescuento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtInsertar)
                        .addGap(38, 38, 38)
                        .addComponent(jbtEliminar)
                        .addGap(27, 27, 27)
                        .addComponent(jbtActualizar)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtRetroceder)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIDDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRetrocederActionPerformed
        InicioAdministrador administrador = new InicioAdministrador();
        administrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtRetrocederActionPerformed

    private void jbtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActualizarActionPerformed
        Double descNuevo = Double.valueOf(jtfDescuento.getText().replace(",", "."));
        Double t = Double.valueOf(jtfTiempo.getText().replace(",", "."));
        int id = Integer.parseInt(jtfIDDescuento.getText());
        Descuento des = new Descuento();
        des.setId_descuento(id);
        des.setDescuento(descNuevo);
        des.setTiempo(t);
        if (daoRegistro.actuDescuento(des)) {
            jtbTarifario.setModel(imprimirDatos());
            vaciar();
        }else{
            JOptionPane.showMessageDialog(null, "El ID del descuento que intenta actualizar no esta registrado, intente con otro.");
        }
    }//GEN-LAST:event_jbtActualizarActionPerformed

    private void jbtInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInsertarActionPerformed
        Double descNuevo = Double.valueOf(jtfDescuento.getText().replace(",", "."));
        Double t = Double.valueOf(jtfTiempo.getText().replace(",", "."));
        int id = Integer.parseInt(jtfIDDescuento.getText());
        Descuento des = new Descuento();
        des.setId_descuento(id);
        des.setDescuento(descNuevo);
        des.setTiempo(t);
        Descuento descu = daoRegistro.buscarDesc(id);
        if (descu == null) {
            daoRegistro.insertarDescuento(des);
            jtbTarifario.setModel(imprimirDatos());
            vaciar();
        }else{
            JOptionPane.showMessageDialog(null, "El ID del descuento que intenta ingresar ya esta registrado, intente con otro.");
        }
    }//GEN-LAST:event_jbtInsertarActionPerformed

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
        if (daoRegistro.eliminarDescuento(Integer.parseInt(jtfIDDescuento.getText()))) {
            jtbTarifario.setModel(imprimirDatos());
            vaciar();
        }else{
            JOptionPane.showMessageDialog(null, "El ID del descuento que intenta actualizar no esta registrado, intente con otro.");
        }
    }//GEN-LAST:event_jbtEliminarActionPerformed

    private void jtfIDDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIDDescuentoKeyTyped
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(null, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_jtfIDDescuentoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtActualizar;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtInsertar;
    private javax.swing.JButton jbtRetroceder;
    private javax.swing.JTable jtbTarifario;
    private javax.swing.JTextField jtfDescuento;
    private javax.swing.JTextField jtfIDDescuento;
    private javax.swing.JTextField jtfTiempo;
    // End of variables declaration//GEN-END:variables
}
