package Interfas;

import Base_De_Datos.DaoRegistro;
import clases.Cupon;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AdministrarCupones extends javax.swing.JFrame {

    DaoRegistro daoRegistro = new DaoRegistro();

    public AdministrarCupones() {
        initComponents();
        jtbTarifario.setModel(imprimirDatos());
        jtbTarifario.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent event) {
                JTable table = (JTable) event.getSource();
                Point point = event.getPoint();
                int row = table.rowAtPoint(point);
                if (event.getClickCount() == 1) {
                    jtfIDCupon.setText(jtbTarifario.getValueAt(jtbTarifario.getSelectedRow(), 0).toString());
                    jtfDescuento.setText(jtbTarifario.getValueAt(jtbTarifario.getSelectedRow(), 1).toString());
                }
            }
        });
    }

    private DefaultTableModel imprimirDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID del Cupon");
        modelo.addColumn("Descuento (S/.)");
        List<Cupon> cupons = daoRegistro.cuponSel();
        for (Cupon c : cupons) {
            String desc = String.format("%.2f", c.getDescuento());
            modelo.addRow(new Object[]{c.getId_cupon(), desc});
        }
        return modelo;
    }

    private void vaciar() {
        jtfDescuento.setText("");
        jtfIDCupon.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtRetroceder = new javax.swing.JButton();
        jbtAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTarifario = new javax.swing.JTable();
        jtfIDCupon = new javax.swing.JTextField();
        jtfDescuento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 35, 35));

        jbtRetroceder.setBackground(new java.awt.Color(36, 35, 35));
        jbtRetroceder.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.jpeg"))); // NOI18N
        jbtRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRetrocederActionPerformed(evt);
            }
        });

        jbtAñadir.setBackground(new java.awt.Color(249, 127, 6));
        jbtAñadir.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtAñadir.setText("Añadir");
        jbtAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAñadirActionPerformed(evt);
            }
        });

        jtbTarifario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTarifario);

        jtfIDCupon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jtfDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Cupon:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de descuento");

        jbtEliminar.setBackground(new java.awt.Color(249, 127, 6));
        jbtEliminar.setFont(new java.awt.Font("Racing Sans One", 0, 18)); // NOI18N
        jbtEliminar.setText("Eliminar");
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtRetroceder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jtfIDCupon, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jtfDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtAñadir)
                .addGap(95, 95, 95)
                .addComponent(jbtEliminar)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtRetroceder)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIDCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRetrocederActionPerformed
        InicioAdministrador administrador = new InicioAdministrador();
        administrador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtRetrocederActionPerformed

    private void jbtAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAñadirActionPerformed
        Double descNuevo = Double.valueOf(jtfDescuento.getText().replace(",", "."));
        Cupon c = new Cupon();
        c.setId_cupon(jtfIDCupon.getText());
        c.setDescuento(descNuevo);
        Cupon cup = daoRegistro.buscarCupon(jtfIDCupon.getText());
        if (cup == null) {
            daoRegistro.insertarCupon(c);
            jtbTarifario.setModel(imprimirDatos());
            vaciar();
        }else{
            JOptionPane.showMessageDialog(null, "El ID del cupon que intenta ingresar ya esta registrado, intente con otro.");
        }

    }//GEN-LAST:event_jbtAñadirActionPerformed

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
        daoRegistro.eliminarCupon(jtfIDCupon.getText());
        jtbTarifario.setModel(imprimirDatos());
        vaciar();
    }//GEN-LAST:event_jbtEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAñadir;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtRetroceder;
    private javax.swing.JTable jtbTarifario;
    private javax.swing.JTextField jtfDescuento;
    private javax.swing.JTextField jtfIDCupon;
    // End of variables declaration//GEN-END:variables
}
